### ISSUE TITLE
Are there tests?

### ISSUE THREAD

**Issue by jamestalmage** [MatAtBread/acorn-es7-plugin#1]
I'd like to use this in something I am working on, but it will be a hard sell to bring in a project without tests.

Is this part of a larger project somewhere?

**Comment by MatAtBread** [comment]
Yes, it's used in nodent (https://github.com/MatAtBread/nodent), which has a bunch of tests via `npm test`. You can also run it against arbitrary JS files - I've run it against over 200,000 now - to ensure the parsing-output-parsing path produces identical trees & code. The command for that test is `./nodent.js tests--syntaxonly <path-to-js-files>`.

I hope that helps. I might even get around to moving the tests from nodent into here

**Comment by jamestalmage** [comment]
cool, thanks!
