### ISSUE TITLE
can it support acorn_loose mode

### ISSUE THREAD

**Issue by CandySunPlus** [MatAtBread/acorn-es7-plugin#13]
if it support acorn_loose mode, I can use it in ternjs

**Comment by MatAtBread** [comment]
Short answer - I've not tried, and I'm unsure what changes (if any) are required. Have you tried it and identified a problem?

**Comment by rkistner** [comment]
I've had a quick attempt at making the plugin work with acorn_loose. Unfortunately the loose parser seems to differ quite significantly from the normal parser (both internal state representation and methods exposed), so it's not as easy as just making a few fixes.

**Comment by MatAtBread** [comment]
I'll take a look and see what can be hacked. Do you have a (simple) test harness that uses loose mode?

**Comment by rkistner** [comment]
I just changed the test.js file to use acorn_loose: https://gist.github.com/rkistner/17593f8921827a75889d85853fc7b50e

I just came across https://github.com/ternjs/acorn/pull/446, which implements async/await for both the normal and loose parsers (but in the core, not as a plugin).

**Comment by matAtWork** [comment]
Thanks for pointing that out. The plugin is (clearly) an interim thing, and so I'll hold off investigating this  issue for a while, in the hope async/await get into the core parser soon
