### ISSUE TITLE
async used as identifier breaks when it is a function name with a function argument

### ISSUE THREAD

**Issue by ArtemGovorov** [MatAtBread/acorn-es7-plugin#14]
Code to reproduce:

``` javascript
var acorn = require('acorn');
require('acorn-es7-plugin')(acorn);

var code = 'async(() => {})';

acorn.parse(code, {
    plugins: {asyncawait: true},
    ecmaVersion: 7
});
```

throws `SyntaxError: Unexpected token (1:14)`

**Comment by matAtWork** [comment]
Excellent catch. Thanks for pointing this out. I have some dependent tests to check against (and a README to update), but unless it causes a problem elsewhere I'll publish to npm later today

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the fast fix!
