### ISSUE TITLE
async in anonymous function

### ISSUE THREAD

**Issue by Tunga37** [MatAtBread/acorn-es7-plugin#16]
If script starts with (async function () ...
parser throws "SyntaxError: Unexpected token (1:7)"

**Comment by matAtWork** [comment]
Please provide more detail. Note that a script cannot start with an anonymous function (async or not) - the function must either be named, or within an expression - for example within parentheses. This is JavaScript requirement.

**Comment by matAtWork** [comment]
The following code seems to work for me: 

http://nodent.mailed.me.uk/#(async%20function(x)%20%7B%0A%20%20%20%20return%20x%20%3B%0A%7D)(%22abc%22).then(y%20%3D%3E%20console.log(y))%0A~options~%7B%22mode%22%3A%22promises%22%2C%22promiseType%22%3A%22Zousan%22%2C%22noRuntime%22%3Afalse%2C%22es6target%22%3Afalse%2C%22wrapAwait%22%3Afalse%2C%22spec%22%3Afalse%7D

**Comment by Tunga37** [comment]
this simple node.js's script throws SyntaxError: Unexpected token (1:7)
```javascript
    (function () {
    "use strict";
    const acorn = require('acorn'); // 3.x
    require('acorn-es7-plugin')(acorn);
    var code = "(async function (){ console.log('hello'); }());";
    var ast = acorn.parse(code,{
        // Specify use of the plugin
        plugins:{asyncawait:true},
        // Specify the ecmaVersion
        ecmaVersion: 7
    }) ;
    // Show the AST
    console.log(JSON.stringify(ast,null,2)) ;
   }());

**Comment by matAtWork** [comment]
You're right. If you wrap the async function in parentheses, it works:

```
var code = "((async function (){ console.log('hello'); })());";
```
(or even)
```
var code = "(async function (){ console.log('hello'); })();";
```

...but without it fails. I'll try to fix it today.

**Comment by matAtWork** [comment]
And it appears not to be an issues with acorn v4 or v5

**Comment by matAtWork** [comment]
Fixed in https://github.com/MatAtBread/acorn-es7-plugin/releases/tag/1.1.7. I'll run integration tests and publish to npm shortly. Thanks for the report :)

**Comment by Tunga37** [comment]
Thanks it works for acorn 3, but are you sure it works also for acorn 4 or 5? Because doesn't work for me. Can you put some example how to do it in upper versions?

**Comment by Tunga37** [comment]
My mistake, i had ecmaVersion: 7 instead of 8

**Comment by matAtWork** [comment]
NP. Let me know if you run into other problems
