### ISSUE TITLE
Example doesn't seem to work with accorn v5 

### ISSUE THREAD

**Issue by zmarouf** [MatAtBread/acorn-es7-plugin#17]
Hello!

I wanted to try my hands at Javascript parsing and acorn and its plugin ecosystem looked neat.
I couldn't get your example to run with acorn@5 (Simple function declaration).
This is the error I get running on LTS/Boron (6.10.2), acorn@5.0.3 and acorn-es7-plugin@1.1.7
```SyntaxError: Unexpected token (1:6)```
 I checked your git log and changelog and noticed you had bumped your test suite so I tried with acorn@4.0.11 but the issue is there too. However, acorn@3.3.0 seems to be compatible.

If you're already aware of this, then sorry for the long read. If you need help testing, do let me know.

Thanks!

**Comment by matAtWork** [comment]
I'm not sure which example you mean - can you supply your code? (or command line)

**Comment by zmarouf** [comment]
It's the example in the Usage section of your README.
Acorn v5:
![acorn e6](https://cloud.githubusercontent.com/assets/4321056/24791487/931a6bd6-1b7a-11e7-9d11-b55d5f059af1.gif)
Acorn v3:
![acorn2](https://cloud.githubusercontent.com/assets/4321056/24791935/54ea4c62-1b7c-11e7-9748-28b88e02fca0.gif)

**Comment by matAtWork** [comment]
In acorn v5 (and I think v4), you need to set `ecmaVersion` to `8`, as the original specifications didn't actually make it into the final ECMA 2015 standard. 

I've updated the README for the next release.

Please re-open if this doesn't fix your issue.
