### ISSUE TITLE
Provide a LICENSE file so we can attribute your work properly and legally!

### ISSUE THREAD

**Issue by caitp** [MatAtBread/acorn-es7-plugin#6]
The title says it all --- I'm investigating supplementing Chromium's devtools with this project, and it would be very nice if we had a proper document to attribute your work. I think legally I can just make something up which includes your full name, but I would feel a lot better if you produce a LICENSE file yourself.

**Comment by matAtWork** [comment]
My pleasure.

**Comment by matAtWork** [comment]
Looking at https://github.com/ternjs/acorn/issues/414#issuecomment-219723060, if you find something it doesn't do, please let me know

**Comment by caitp** [comment]
Reading the code, it looks like the `[NoLineTerminatorHere]` handling (which seems to be performed by a RegExp) will fail completely if there is a comment between the `async` token and the remaining tokens, so I expect that will not work. For instance, it looks like it will treat `async // if true, non-serial execution<linefeed>` will be parsed as an async function, because the parser is not aware that the next token is on a different line.

I'm verifying this at the moment, will file an issue if it's a problem

**Comment by matAtWork** [comment]
That seems like a distinct possibility. It you can come up with a simple breaking case, I'll have a go at fixing it

**Comment by MatAtBread** [comment]
You're right. I'll try and fix in the next few days. See https://github.com/MatAtBread/acorn-es7-plugin/issues/7
