### ISSUE TITLE
Incorrect parsing of nested awaits with awaitAnywhere

### ISSUE THREAD

**Issue by rksm** [MatAtBread/acorn-es7-plugin#9]
Test code:

``` js
var options = {
  ecmaVersion: 7,
  plugins: {asyncawait : {awaitAnywhere: true}}
};

acorn.parse("await (await foo()).bar()", options);
```

Expected structure:

```
:Program
\-.body[0]:ExpressionStatement
  \-.body[0].expression:AwaitExpression
    \-.body[0].expression.argument:CallExpression
      \-.body[0].expression.argument.callee:MemberExpression
        |-.body[0].expression.argument.callee.object:AwaitExpression
        | \-.body[0].expression.argument.callee.object.argument:CallExpression
        |   \-.body[0].expression.argument.callee.object.argument.callee:Identifier
        \-.body[0].expression.argument.callee.property:Identifier
```

Actual structure

```
:Program
\-.body[0]:ExpressionStatement
  \-.body[0].expression:CallExpression
    \-.body[0].expression.callee:MemberExpression
      |-.body[0].expression.callee.object:CallExpression
      | |-.body[0].expression.callee.object.callee:Identifier
      | \-.body[0].expression.callee.object.arguments[0]:AwaitExpression
      |   \-.body[0].expression.callee.object.arguments[0].argument:CallExpression
      |     \-.body[0].expression.callee.object.arguments[0].argument.callee:Identifier
      \-.body[0].expression.callee.property:Identifier
```

In other words the await is mistaken as callee. When stringifying the result one gets: `await(await foo()).bar();`

**Comment by MatAtBread** [comment]
Unless I'm mistaken, this is a (documented) issue with parsing with `awaitAnywhere` - without knowing the context (i.e. inside an async function), there is no way to disambiguate between a call `await(x)` and the `await` operator.

In an async function, this is unambiguous (await is a reserved word). Outside an async function, it is also unambiguous (it's a call). The issue with 'awaitAnywhere` is it doesn't know.

Is this really a request to add another flag (eg. `inAsyncFunction`) that makes the former assumption? In that case, you would (of course) need to parse the outer-code to work out whether to set the flag, which is what the plugin does by default.

**Comment by rksm** [comment]
Thanks! 👍

**Comment by MatAtBread** [comment]
NP. Let me know if it doesn't do what you expect
